config/routes.rb
Rails.application.routes.draw do


  # get 'users/new'

  get 'home/index'
  get 'faq', to: "home#faq", as: 'faq'
  resources :services
  get '/service_index_admin', to: 'services#index_admin'
  get '/functional_evaluation', to: 'services#functional_evaluation'
  get '/cost_of_future_care', to: 'services#cost_of_future_care'
  get '/medical_legal_consultation', to: 'services#medical_legal_consultation'
  get '/community_rehabilitation', to: 'services#community_rehabilitation'
  get '/physiotherapy', to: 'services#physiotherapy'
  get '/functional_conditioning', to: 'services#functional_conditioning'
  get '/interdisciplinary_rehabilitation', to: 'services#interdisciplinary_rehabilitation'
  get '/job_demands_analyses', to: 'services#job_demands_analyses'
  get '/ergononmic_risk_factor_analyses', to: 'services#ergononmic_risk_factor_analyses'
  get '/clinical_counselling_services', to: 'services#clinical_counselling_services'
  get '/psychology_assessment', to: 'services#psychology_assessment'
  resources :about_us, only: [:index]
  resources :testimonials
  resources :careers, only: [:index, :show]
  resources :contacts
  get '/surrey', to: "contacts#surrey"
  get '/vancouver', to: "contacts#vancouver"
  get '/coquitlam', to: "contacts#coquitlam"
  get '/abbotsford', to: "contacts#abbotsford"
  get '/victoria', to: "contacts#victoria"
  get '/nanaimo', to: "contacts#nanaimo"
  get '/kelowna', to: "contacts#kelowna"

  resources :admin_dashboard, only: [:index]
  resources :our_teams
  get '/office_administration', to: "our_teams#office_administration"
  get '/occupational_therapists', to: "our_teams#occupational_therapists"
  get '/physiotherapists', to: "our_teams#physiotherapists"
  get '/kinesiologist', to: "our_teams#kinesiologist"
  get '/memorials', to: "our_teams#memorial"
  get '/psychology', to: "our_teams#psychology"
  get '/psychiatrist', to: "our_teams#psychiatrist"
  get '/counsellors', to: "our_teams#counsellors"
  get '/medlegal', to: "referrals#medlegal"
  get '/employer', to: "referrals#employer"
  get '/covid_19', to: "coronas#index"
  resources :users
  resources :admin_teams
  get '/index_original', to: "admin_teams#index_original"
  post 'team_archive/:id', to: "admin_teams#archive", as:'team_archive'
  resources :members
  resources :admin_careers
  resources :admin_testimonials
  resources :admin_enquiries
  resources :job_applications

  post 'testimonial_archive/:id', to: "admin_testimonials#archive", as:'testimonial_archive'
  post 'careers_archive/:id', to: "admin_careers#archive", as:'career_archive'

  resources :admin_enquiries
  resources :referrals

  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :admin_referrals
  resources :info_referrals
  resources :locations


  get '*path' => redirect('/')

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_career.rb
class AdminCareer < ApplicationRecord
  mount_uploader :career, ImageUploader
  validates :title, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :career, presence: true

end

app/models/admin_enquiry.rb
class AdminEnquiry < ApplicationRecord
end

app/models/admin_referral.rb
class AdminReferral < ApplicationRecord
  require 'sendgrid-ruby'
  include SendGrid
  # validates :client_name, presence: true
  # validates :name, presence: true
  # validates :company, presence: true
  # validates :phone, presence: true
  # validates :email, presence: true
  # validates :client_phone, presence: true
  # validates :advertisement, presence: true

  generate_public_uid
  
  def self.find_param(param)
    find_by! public_uid: param.split('-').first
  end

  after_create :add_categorizer_to_confirmation_code

  private

  def add_categorizer_to_confirmation_code
    loop do
      public_uid = self.public_uid
      public_uid = public_uid.prepend('M') if self.referral_form_type == 'medlegal'
      public_uid = public_uid.prepend('E') if self.referral_form_type == 'employer'
      break unless AdminReferral.exists?(public_uid: public_uid)
    end
    self.update_column(:public_uid, public_uid)
  end

  def send_mail_to_creator
    from = Email.new(email: 'test@example.com')
    to = Email.new(email: 'test@example.com')
    subject = 'Sending with SendGrid is Fun'
    content = Content.new(type: 'text/plain', value: 'and easy to do anywhere, even with Ruby')
    mail = Mail.new(from, subject, to, content)

    sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
    response = sg.client.mail._('send').post(request_body: mail.to_json)
  end
end

app/models/admin_team.rb
class AdminTeam < ApplicationRecord
  belongs_to :job_category
  mount_uploader :image, ImageUploader
  mount_uploader :resume, ResumeUploader

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :image, presence: true

  def memorial?
    state = false
    memorial_category_id = JobCategory.find_by(title: 'Memorial').id
    state = true if self.job_category_id == memorial_category_id
    state
  end
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  mount_uploader :resume, ApplyUploader
end

app/models/job_category.rb
class JobCategory < ApplicationRecord
  has_many :admin_teams
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  mount_uploader :image, ImageUploader
  
end

app/models/service.rb
class Service < ApplicationRecord
  mount_uploader :picture, ServiceImageUploader

  validates :title, presence: true
  validates :picture, presence: true
  validates :content, presence: true
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true

  has_secure_password
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :logged_in_check, only: [:index_admin, :new, :edit]

  def index
    @admin_enquiry = AdminEnquiry.new
    @services = Service.all
    @services = @services.sort_by {|x| x.display_number}
    @admin_enquiry = AdminEnquiry.new
  end

  def index_admin
    @services = Service.all
    @admin_enquiry = AdminEnquiry.new
    # binding.pry
  end

  def show
    @service = Service.find(params[:id])
    @services = Service.all
    @services = @services.sort_by {|x| x.display_number}
    @admin_enquiry = AdminEnquiry.new
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      redirect_to service_index_admin_path
    else
      render 'new'
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    if @service.update(service_params)
      redirect_to service_index_admin_path
    else
      render 'edit'
    end

  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to service_index_admin_path
  end


  def functional_evaluation
    # Done
  end

  def cost_of_future_care
  end

  def medical_legal_consultation
  end

  def community_rehabilitation
  end

  def physiotherapy
  end

  def functional_conditioning
  end

  def interdisciplinary_rehabilitation
  end

  def job_demands_analyses
  end

  def ergononmic_risk_factor_analyses
  end

  def clinical_counselling_services
  end

  def psychology_assessment
  end

  private

  def service_params
    params.require(:service).permit(:title,:content,:picture,:description,:display_number,:referral_type)
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/coronas_helper.rb
module CoronasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/our_teams_helper.rb
module OurTeamsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/services/_form.html.erb
<% if @service.errors.any? %>
  <div id="error_explanation">
   <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

   <ul>
   <% @service.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
  </div>
<% end %>
<%= form_for(@service) do |f| %>
<div class="container card-inner-padding">
  <div class="row justify-content-between mg-left card-margin-bottom">
    <div>

      <%= f.label :picture %><br>
      <%= f.file_field :picture,  onchange:"readURL(this)"%>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
         <img id="img_prev" src="#" alt="Image Preview" />
    </div>

    <div class="col-sm-6">
      <div class="row">
        <div class="col-sm-12 margin-bottom-11" style="padding-left: 0px;">
          <%= f.text_field :title, class:"form-control input-box", placeholder: "Title" %>
        </div>
        <div class="col-sm-12 margin-bottom-11" style="padding-left: 0px;">
          <%= f.number_field :display_number, class:"form-control input-box", placeholder: "Display Number" %>
        </div>
        <div class="col-sm-12 margin-bottom-11" style="padding-left: 0px;">
          <%= f.select :referral_type,  ["legal","rehab","both"], {},{class: 'form-control input-box'} %>
        </div>
      </div>
    </div>
    <div class="col-sm-12 card-margin-top">
      <%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 30 %>
      <%= tinymce %>
    </div>
    <div class="col-sm-12 card-margin-top">
      <%= f.submit "Save", class:"admin-button-blue" %>
    </div>
  </div>
<% end %>

app/views/services/edit.html.erb
<div class="admin-nav">
  <a class="navbar-brand" href="#"><%= image_tag("refunction_nav_logo.svg", class:"admin-logo") %>
  </a>
    <%= link_to "Log Out", logout_path, class:"btn admin-log-out-btn", method: :delete %>
</div>

<div class="container-fluid">
  <div class="row">
    <%= render 'layouts/admin_nav' %>

    <div class="admin-body col-sm-10">
      <div class="admin-card">
        <div class="container-fluid">
          <div class="row">
            <div class="search-top col-sm-12 pd-top-10">
              <p>New Services</p>
            </div>
          </div>
        </div>
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>


<!-- Assume jQuery is loaded -->
    <script>
      function readURL(input) {
        if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
            $('#img_prev')
              .attr('src', e.target.result)
              .width(300)
              .height(250);
          };

          reader.readAsDataURL(input.files[0]);
        }
      }
    </script>

app/views/services/ergononmic_risk_factor_analyses.html.erb
<%= render "layouts/nav" %>
<%= render "layouts/banner_top_deco" %>



<div class="our_services pages-card-padding">
  <div class="container">
    <div class="row">

      <%= render 'link' %>

      <div class="offset-sm-1 col-sm-8">
        <div class="row mb-padding-top-15">
          <%= image_tag("Ergonomic and Risk Factor Analysess.jpg", class:"card-img-top mb-img-height-100", style:"height: 450px;") %>
          <div style="font-size: 8px;opacity: 0.7;color: grey;">© Re:Function Health Group All Rights Reserved</div>
        </div>
        <div class="row black-with-dots">
          <p class="show-header">Ergonomic and Risk Factor Analyses</p>
          <p class="show-font black-with-dots">
            These analyses examine the work procedures and physical environments of particular jobs to determine whether thresholds for risk factors known to develop musculoskeletal disorders has reached or exceeded. Reports for these analyses include recommendations for ergonomic solutions to optimize comfort and function while working.
          </p>
        </div>
      </div>

    </div>
  </div>
</div>

<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>

app/views/services/index2.html.erb
<%= render "layouts/nav" %>
<%= render "layouts/banner_top_deco" %>



<div class="our_services main-card-padding">
  <div class="container">
    <div class="row justify-content-between ">
      <div class=" col-md-12 col-lg-3 mb-margin-top-40" style="margin-bottom: 20px;">
        <div class="list_of_services_box mb-mg-bottom">
          <h5>Learn about our services</h5>
          <div class="highlight"></div>
          <ul>
            <% @services.each do |f| %>
            <li><%= link_to "#{f.title}", service_path(f) %></li>
            <% end %>
            <!-- <li><a href="/functional_evaluation">Functional Capacity Evaluations</a></li>
            <li><a href="/cost_of_future_care">Cost of Future Care Evaluations</a></li>
            <li><a href="/medical_legal_consultation">Medical Legal Consultations</a></li>
            <li><a href="/community_rehabilitation">Community Rehabilitation Services</a></li>
            <li><a href="/physiotherapy">Physiotherapy Services</a></li>
            <li><a href="/functional_conditioning">Active Rehab Programs</a></li>
            <li><a href="/interdisciplinary_rehabilitation">Interdisciplinary Rehabilitation Assessments</a></li>
            <li><a href="job_demands_analyses">Job Demands Analyses</a></li>
            <li><a href="ergononmic_risk_factor_analyses">Ergonomic and Risk Factor Analyses</a></li>
            <li><a href="clinical_counselling_services">Clinical Counselling Services</a></li> -->

          </ul>
        </div>
      </div>

      <div class="col-md-12 col-lg-9">
        <div class="row">
          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("Physiotherapy_services.jpg", class:"card-img-top", style:"max-height:200px; max-width: 300px;") %>
            <div style="font-size: 8px;opacity: 0.7;color: grey;">© Re:Function Health Group All Rights Reserved</div>
            <div >
              <a href="/physiotherapy"><p class="services-card-font">Physiotherapy</p></a>
            </div>
          </div>

          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("community rehabilitation_v2.jpg", class:"card-img-top", style:"max-height:200px; max-width: 300px;") %>
            <div style="font-size: 8px;opacity: 0.7;color: grey;">© Re:Function Health Group All Rights Reserved</div>
            <div >
              <a href="/community_rehabilitation"><p class="services-card-font">Community Rehabilitation Services</p></a>
            </div>
          </div>

          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("Counselling.jpg", class:"card-img-top", style:"max-height:200px; max-width: 300px;") %>
            <div style="font-size: 8px;opacity: 0.7;color: grey;">© Re:Function Health Group All Rights Reserved</div>
            <div >
              <a href="/clinical_counselling_services"><p class="services-card-font">Clinical Counselling Services</p></a>
            </div>
          </div>


          <div class="col-12 col-sm-6 card-side-padding mb-mg-bottom">
            <%= image_tag("Services - Functional Capacity Evaluations.jpg", class:"card-img-top", style:"max-height:200px; max-width: 300px;") %>
            <div style="font-size: 8px;opacity: 0.7;color: grey;">© Re:Function Health Group All Rights Reserved</div>
            <div>
              <a href="/functional_evaluation"><p class="services-card-font">Functional Capacity Evaluations</p></a>
            </div>
          </div>



          <div class="col-12 col-sm-6 card-side-padding mb-mg-bottom">
            <%= image_tag("Cost of Future Care.jpg", class:"card-img-top", style:"max-height:200px; max-width: 300px;") %>
            <div style="font-size: 8px;opacity: 0.7;color: grey;">© Re:Function Health Group All Rights Reserved</div>
            <div>
              <a href="/cost_of_future_care"><p class="services-card-font">Cost of Future Care Evaluation</p></a>
            </div>
          </div>

          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("Medical Legal Consultations.jpg", class:"card-img-top", style:"max-height:200px; max-width: 300px;") %>
            <div style="font-size: 8px;opacity: 0.7;color: grey;">© Re:Function Health Group All Rights Reserved</div>
            <div >
              <a href="/medical_legal_consultation"><p class="services-card-font">Medical Legal Consultations</p></a>
            </div>
          </div>

          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("Active and Functional Conditioning.jpg", class:"card-img-top", style:"max-height:200px; max-width: 300px; height: 100%;") %>
            <div style="font-size: 8px;opacity: 0.7;color: grey;">© Re:Function Health Group All Rights Reserved</div>
            <div >
              <a href="/functional_conditioning"><p class="services-card-font">Active and Functional Conditioning</p></a>
            </div>
          </div>

          <!-- <div class="col-12 col-sm-6 card-side-padding">
            <#%= image_tag("Community Rehabilitation.jpg", class:"card-img-top", style:"max-height:200px;") %>
            <div >
              <a href="/community_rehabilitation"><p class="services-card-font">Community Rehabilitation</p></a>
            </div>
          </div> -->

          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("Interdisciplinary Rehabilitation Assessments.jpg", class:"card-img-top", style:"max-height:200px; max-width: 300px; height: 200px;") %>
            <div style="font-size: 8px;opacity: 0.7;color: grey;">© Re:Function Health Group All Rights Reserved</div>
            <div >
              <a href="/interdisciplinary_rehabilitation"><p class="services-card-font">Interdisciplinary Rehabilitation Assessments</p></a>
            </div>
          </div>

          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("Job Demands Analysis.jpg", class:"card-img-top", style:"max-height:200px; max-width: 300px;") %>
            <div style="font-size: 8px;opacity: 0.7;color: grey;">© Re:Function Health Group All Rights Reserved</div>
            <div >
              <a href="/job_demands_analyses"><p class="services-card-font">Job Demand Analyses</p></a>
            </div>
          </div>

          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("Ergonomic and Risk Factor Analysess.jpg", class:"card-img-top", style:"max-height:200px; max-width: 300px;") %>
            <div style="font-size: 8px;opacity: 0.7;color: grey;">© Re:Function Health Group All Rights Reserved</div>
            <div >
              <a href="/ergononmic_risk_factor_analyses"><p class="services-card-font">Ergonomic and Risk Factor Analyses</p></a>
            </div>
          </div>


        </div>

        <!-- <div class="row">
          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("refunction_home_services.png", class:"card-img-top") %>
            <div >
              <p class="services-card-font">Balanced Disability Assessment</p>
            </div>
          </div>

          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("refunction_home_services.png", class:"card-img-top") %>
            <div >
              <p class="services-card-font">Balanced Disability Assessment</p>
            </div>
          </div>

          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("refunction_home_services.png", class:"card-img-top") %>
            <div >
              <p class="services-card-font">Balanced Disability Assessment</p>
            </div>
          </div>
        </div> -->

        <!-- <div class="row">
          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("refunction_home_services.png", class:"card-img-top") %>
            <div >
              <p class="services-card-font">Balanced Disability Assessment</p>
            </div>
          </div>

          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("refunction_home_services.png", class:"card-img-top") %>
            <div >
              <p class="services-card-font">Balanced Disability Assessment</p>
            </div>
          </div>

          <div class="col-12 col-sm-6 card-side-padding">
            <%= image_tag("refunction_home_services.png", class:"card-img-top") %>
            <div >
              <p class="services-card-font">Balanced Disability Assessment</p>
            </div>
          </div>
        </div> -->

      </div>


    </div>
  </div>
</div>

<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>

app/views/services/index_admin.html.erb
<div class="admin-nav">
  <a class="navbar-brand" href="#"><%= image_tag("refunction_nav_logo.svg", class:"admin-logo") %>
  </a>
  <button class="admin-log-out-btn"> Log out</button>
</div>

<div class="container-fluid">
  <div class="row">

    <%= render 'layouts/admin_nav' %>


    <div class="admin-body col-sm-10">
      <div class="admin-team-search-bar">
        <div class="container-fluid">
          <div class="row">
            <div class="search-top col-sm-12">
              <p>Published Job Posting</p>
            </div>
          </div>
          <div class="row admin-search-padding">
            <div class="col-sm-12">
              <div class="row">
                <div class="offset-sm-9 col-sm-3">
                    <a href="/services/new"><div class="admin-search-button mg-bottom"> Add New</div></a>
                </div>
                <div class="col-sm-12">
                  <div class="row">
                    <% @services.each do |f| %>
                    <div class="col-sm-6 mg-bottom">
                      <div class="careers-box">
                        <div class="row">
                          <div class="col-sm-4 careers-image" style="padding-left: 0px; padding-right: 0px;">
                            <!-- <#%= image_tag("refunction_home_services.png") %> -->
                            <%= image_tag f.picture.url, style:"max-height: 200px;"%>
                          </div>
                          <div class="col-sm-8 reset" style="padding-left: 5px;padding-right: 0px;">
                            <div class="card-body reset" style="padding-top: 0px;padding-bottom: 0px;padding-left: 0px;padding-right: 0px;">
                              <div>
                                <span class="careers-posting-date">Posted June 30, 2018</span>
                              </div>
                              <div>
                                <span class="careers-posting-title bold"><%= f.title %></span>
                              </div>

                              <div class="highlight-thin careers-posting-highlight"></div>
                              <p class="card-text text-pd-right" style="font-size: 0.7em; margin-bottom: 3px;"><%= f.content.truncate(200) %>
                              </p>

                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="admin-staff-image-button">
                        <div class="btn btn-primary font-white">
                          <%= link_to "Edit", edit_service_path(f) %>
                        </div>

                        <div class="btn btn-danger font-white">
                          <%= link_to "Delete", service_path(f), method: :delete, data: {confirm: "Are you sure?"} %>
                        </div>
                      </div>
                    </div>
                    <% end %>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>






    </div>
  </div>
</div>

app/views/services/show.html.erb
<%= render "layouts/nav" %>
<%= render "layouts/banner_top_deco" %>



<div class="our_services pages-card-padding">
  <div class="container">
    <div class="row">

      <%= render 'link' %>

      <div class="offset-sm-1 col-sm-8">
        <div class="row mb-padding-top-15">
            <%= image_tag @service.picture.url, class:"img-fluid services-show" %>
          <div style="font-size: 8px;opacity: 0.7;color: grey;">© Re:Function Health Group All Rights Reserved</div>
        </div>
          <p class="show-header"><%= @service.title %></p>
          <p style="color: black;">
            <%= raw(@service.content) %>
          </p>
          <p style="color: black;">
            <% if @service.referral_type == "legal" %>
              <span> To proceed with this service, </span><span><a href="/medlegal">click here </a></span>
            <% elsif @service.referral_type == "rehab" %>
              <span> To proceed with this service, </span><span><a href="/employer">click here </a></span>
            <% elsif @service.referral_type == "both" %>
              <span> For medical legal evaluations, </span><span><a href="/medlegal">click here </a></span>
              <br>
              <span> For non-medical legal evaluations, </span><span><a href="/employer">click here </a></span>
            <% else %>
            <% end %>
        
          </p>

          <div class="row padding-top-50">
            <%= link_to "Back to Services", services_path, class:"cta-see-team"%>
          </div>

      </div>


    </div>
  </div>
</div>


<%= render "layouts/bottom_cta_card" %>

<div class="footer main-card-padding">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <h5 class="bold">Contact Information</h5>
        <div class="highlight-small"></div>
        <ul>
          <li><a href="https://www.google.com/maps/place/21300+Gordon+Way,+Richmond,+BC+V6W+1J8/@49.166436,-122.987695,16z/data=!4m5!3m4!1s0x5485df362b3f5cb1:0x28e783c3398af216!8m2!3d49.1664355!4d-122.9876951?hl=en-CA", style="color: gray">148 – 21300 Gordon Way Richmond BC V6W 1M2</a></li>

          <li><a href="tel:+1604-233-2210" style="color: gray">Tel: 604.233.2210</a></li>
          <li><a href="tel:+1604-233-2211" style="color: gray">Fax: 604.233.2211</a></li>
          <li><a href="mailto:info@refunction.ca" style="color: gray">Email: info@refunction.ca</a></li>
        </ul>
      </div>
      <!-- <div class="col-sm-3">
        <h5 class="bold">Doctors</h5>
        <div class="highlight-small"></div>
        <ul>
          <li><span class="dot"></span>Dr. Nick Sims</li>
          <li><span class="dot"></span>Dr. Max Tuner</li>
          <li><span class="dot"></span>Dr. Amy Adams</li>
          <li><span class="dot"></span>Dr. Nick Sims</li>
          <li><span class="dot"></span>Dr. Max Tuner</li>
          <li><span class="dot"></span>Dr. Amy Adams</li>
        </ul>
      </div> -->
      <div class="col-sm-3 mb-margin-top-25">
        <h5 class="bold">Locations</h5>
        <div class="highlight-small"></div>
        <ul>
          <li><span class="dot"></span><a href="/contacts" style="color: grey">Richmond: Head Office</a></li>
          <li><span class="dot"></span><a href="/surrey" style="color: grey">Surrey Clinic</a></li>
          <li><span class="dot"></span><a href="/vancouver" style="color: grey">Vancouver Clinic</a></li>
          <li><span class="dot"></span><a href="/coquitlam" style="color: grey">Coquitlam Clinic</a></li>
          <li><span class="dot"></span><a href="/abbotsford" style="color: grey">Abbotsford Clinic</a></li>
          <li><span class="dot"></span><a href="/victoria" style="color: grey">Victoria Clinic</a></li>
          <li><span class="dot"></span><a href="/nanaimo" style="color: grey">Nanaimo Clinic</a></li>
        </ul>
      </div>
      <div class="col-sm-6  col-xl-6 col-lg-12 mb-margin-top-25">
        <%= form_for(@admin_enquiry) do |f| %>
        <h5 class="bold">Contact Us</h5>
        <div class="highlight-small"></div>

          <%= f.text_field :first_name, class:"form-control text-area-box", placeholder: "Name" %>


          <%= f.text_field :email, class:"form-control text-area-box", placeholder: "Email"%>


          <%= f.text_field :phone, class:"form-control text-area-box", placeholder: "Phone" %>

        <div class="form-group">
          <%= f.text_area :content, class:"form-control text-area-box", rows:"5"  %>
        </div>
        <button class="footer-submit-btn">Submit</button>
        <div style="padding-top: 15px; overflow: hidden;">
          <%= recaptcha_tags %>
        </div>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>