config/routes.rb
Rails.application.routes.draw do


  # get 'users/new'

  get 'home/index'
  get 'faq', to: "home#faq", as: 'faq'
  resources :services
  get '/service_index_admin', to: 'services#index_admin'
  get '/functional_evaluation', to: 'services#functional_evaluation'
  get '/cost_of_future_care', to: 'services#cost_of_future_care'
  get '/medical_legal_consultation', to: 'services#medical_legal_consultation'
  get '/community_rehabilitation', to: 'services#community_rehabilitation'
  get '/physiotherapy', to: 'services#physiotherapy'
  get '/functional_conditioning', to: 'services#functional_conditioning'
  get '/interdisciplinary_rehabilitation', to: 'services#interdisciplinary_rehabilitation'
  get '/job_demands_analyses', to: 'services#job_demands_analyses'
  get '/ergononmic_risk_factor_analyses', to: 'services#ergononmic_risk_factor_analyses'
  get '/clinical_counselling_services', to: 'services#clinical_counselling_services'
  get '/psychology_assessment', to: 'services#psychology_assessment'
  resources :about_us, only: [:index]
  resources :testimonials
  resources :careers, only: [:index, :show]
  resources :contacts
  get '/surrey', to: "contacts#surrey"
  get '/vancouver', to: "contacts#vancouver"
  get '/coquitlam', to: "contacts#coquitlam"
  get '/abbotsford', to: "contacts#abbotsford"
  get '/victoria', to: "contacts#victoria"
  get '/nanaimo', to: "contacts#nanaimo"
  get '/kelowna', to: "contacts#kelowna"

  resources :admin_dashboard, only: [:index]
  resources :our_teams
  get '/office_administration', to: "our_teams#office_administration"
  get '/occupational_therapists', to: "our_teams#occupational_therapists"
  get '/physiotherapists', to: "our_teams#physiotherapists"
  get '/kinesiologist', to: "our_teams#kinesiologist"
  get '/memorials', to: "our_teams#memorial"
  get '/psychology', to: "our_teams#psychology"
  get '/psychiatrist', to: "our_teams#psychiatrist"
  get '/counsellors', to: "our_teams#counsellors"
  get '/medlegal', to: "referrals#medlegal"
  get '/employer', to: "referrals#employer"
  get '/covid_19', to: "coronas#index"
  resources :users
  resources :admin_teams
  get '/index_original', to: "admin_teams#index_original"
  post 'team_archive/:id', to: "admin_teams#archive", as:'team_archive'
  resources :members
  resources :admin_careers
  resources :admin_testimonials
  resources :admin_enquiries
  resources :job_applications

  post 'testimonial_archive/:id', to: "admin_testimonials#archive", as:'testimonial_archive'
  post 'careers_archive/:id', to: "admin_careers#archive", as:'career_archive'

  resources :admin_enquiries
  resources :referrals

  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :admin_referrals
  resources :info_referrals
  resources :locations


  get '*path' => redirect('/')

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_referral.rb
class AdminReferral < ApplicationRecord
  require 'sendgrid-ruby'
  include SendGrid
  # validates :client_name, presence: true
  # validates :name, presence: true
  # validates :company, presence: true
  # validates :phone, presence: true
  # validates :email, presence: true
  # validates :client_phone, presence: true
  # validates :advertisement, presence: true

  generate_public_uid
  
  def self.find_param(param)
    find_by! public_uid: param.split('-').first
  end

  after_create :add_categorizer_to_confirmation_code

  private

  def add_categorizer_to_confirmation_code
    loop do
      public_uid = self.public_uid
      public_uid = public_uid.prepend('M') if self.referral_form_type == 'medlegal'
      public_uid = public_uid.prepend('E') if self.referral_form_type == 'employer'
      break unless AdminReferral.exists?(public_uid: public_uid)
    end
    self.update_column(:public_uid, public_uid)
  end

  def send_mail_to_creator
    from = Email.new(email: 'test@example.com')
    to = Email.new(email: 'test@example.com')
    subject = 'Sending with SendGrid is Fun'
    content = Content.new(type: 'text/plain', value: 'and easy to do anywhere, even with Ruby')
    mail = Mail.new(from, subject, to, content)

    sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
    response = sg.client.mail._('send').post(request_body: mail.to_json)
  end
end

app/controllers/admin_referrals_controller.rb
class AdminReferralsController < ApplicationController
  before_action :logged_in_check, except: [:create]

  def index
    @referrals = AdminReferral.all.order('created_at desc')
  end

  def show

    # find_param is from the AdminReferral Modal where it searches it based on the public_uid
    # of the record
    @referral = AdminReferral.find_param(params[:id])
  end

  def create
    # binding.pry
    @referral = AdminReferral.new(admin_referral_params)

    if verify_recaptcha(model: @referral) && @referral.save


      ReferralMailer.send_signup_email(@referral).deliver
      ReferralMailer.send_received_email(@referral).deliver
      flash[:success] = "Thank you for your referral. We will contact you shortly"
      redirect_to referrals_path
    else

      flash[:danger] = "Plese fill the required fields!"
      redirect_to referrals_path
    end
  end

  def destroy
    @referral = AdminReferral.find_param(params[:id])
    @referral.destroy
    redirect_to admin_referrals_path
  end

  private

  def admin_referral_params
    params.require(:admin_referral).permit(:category, :client_name, :name, :client_birthday, :company, :client_phone, :claim_number, :client_address, :address, :client_city, :phone, :client_postal_code, :email, :date_of_injury, :client_fax, :client_language, :realation_to_client, :concerns, :client_aware, :advertisement, :content, :client_sex_other, :client_sex, :client_advertisement_other, :client_email, :referral_source_name, :assistant_phone, :assistant_email, :city, :rs_office_address, :rs_name, :rs_phone, :rs_fax, :rs_email, :rs_represents, :rs_city, :rs_postal_code, :rs_assistant_name, :rs_assistant_phone, :rs_assistant_email, :client_id, :client_file_number, :client_date_of_birth, :client_report_deadline, :client_trial_date, :client_trial_duration_in_days, :client_date_of_injury, :client_gender, :client_interpreter_required, :client_language_required, :referral_form_type, :rs_office_name, :client_rebuttal_needed, :client_sub_file_number, :email_confirmation_address)
  end


end

app/helpers/admin_referrals_helper.rb
module AdminReferralsHelper
end

app/views/admin_referrals/_employee.html.erb
<div class="container-fluid main-container">
  <div class="row print-firefox">
    <div class="col-sm-12" >
      <div class="" style="min-height: 900px;">
        <div class="container-fluid">
          <div class="row admin-search-padding print-firefox pdt-0" id='showReferral'>
            <div class="col-sm-12">
              <div class="row print-firefox-inline" style="page-break-after: always;">
                <div class="col-sm-12 margin-bottom-11 career-pd-left-0 pt-1 print-firefox-size">
                  <p class="print-firefox-fontsize" style="font-size: 30px; font-weight: 800;">REFERRAL SOURCE INFORMATION</p>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Category</p>
                  <div class="form-control">
                    <%= @referral.category %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>CM/Employer Contact Name</p>
                  <div class="form-control">
                    <%= @referral.rs_name %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>CM/Employer Contact Phone #</p>
                  <div class="form-control">
                    <%= @referral.rs_phone %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>CM/Employer Contact Fax #</p>
                  <div class="form-control">
                    <%= @referral.rs_fax %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>CM/Employer Contact Email</p>
                  <div class="form-control">
                    <%=  @referral.rs_email %>
                  </div>
                </div>


                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Company/Organization</p>
                  <div class="form-control">
                    <%= @referral.rs_office_name %>
                  </div>
                </div>


                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Address</p>
                  <div class="form-control">
                    <%=  @referral.rs_office_address %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>City</p>
                  <div class="form-control">
                    <%=  @referral.rs_city %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Postal Code</p>
                  <div class="form-control">
                    <%=  @referral.rs_postal_code %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Assistant’s Email</p>
                  <div class="form-control">
                    <%=  @referral.rs_assistant_name %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Assistant Email</p>
                  <div class="form-control">
                    <%=  @referral.rs_assistant_email %>
                  </div>
                </div>

              </div>

              <div class="row mt-4 print-firefox" style="page-break-after: always;">
                <div class="col-sm-12 margin-bottom-11 career-pd-left-0">
                  <p class="print-firefox-fontsize " style="font-size: 30px; font-weight: 800;">CLIENT INFORMATION</p>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Client Name</p>
                  <div class="form-control">
                    <%= @referral.client_name %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Client Address </p>
                  <div class="form-control">
                    <%= @referral.client_address %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Date of Birth</p>
                  <div class="form-control">
                  <% if @referral.client_birthday != nil %>
                    <%= (@referral.client_birthday).strftime("%B %d, %Y") %>
                  <% end %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>City</p>
                  <div class="form-control">
                    <%=  @referral.client_city %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Client Phon #</p>
                  <div class="form-control">
                    <%= @referral.client_phone %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Postal Code</p>
                  <div class="form-control">
                    <%= @referral.client_postal_code %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Client Email</p>
                  <div class="form-control">
                    <%= @referral.client_email %>
                  </div>
                </div>

                <div class='col-sm-6'></div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Policy No.</p>
                  <div class="form-control">
                    <%= @referral.client_file_number %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Client ID No.</p>
                  <div class="form-control">
                    <%= @referral.client_sub_file_number %>
                  </div>
                </div>

                 <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Client Gender</p>
                  <div class="form-control">
                    <%= @referral.client_sex %>
                  </div>
                </div>

                <!-- <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p> Client Gender(other)</p>
                  <div class="form-control">
                    <%#= @referral.client_sex_other %>
                  </div>
                </div> -->

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p> Date Of Injury</p>
                  <div class="form-control">
                    <% if @referral.client_date_of_injury != nil %>
                      <%=  @referral.client_date_of_injury.strftime("%B %d, %Y")%>
                    <% end %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 interpreter-required-result">
                  <p>Is an Interpreter Required?</p>
                  <div class="form-control">
                    <%=  @referral.client_interpreter_required %>
                  </div>
                </div>
                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 interpreter-required-language" style="page-break-after: always;">
                  <div class='d-none'>
                    <p>Required Langauge</p>
                    <div class="form-control">
                      <%=  @referral.client_language_required %>
                    </div>
                  </div>
                </div>

                <div class="col-sm-12 margin-bottom-11 career-pd-left-0 print-show" style="display: none;">
                  <p class="print-firefox-fontsize" style="font-size: 30px; font-weight: 800;">CLIENT INFORMATION</p>
                </div>


                <div class="col-sm-12 margin-bottom-11 career-pd-left-0">
                  <p>Concern</p>
                  <div class="form-control" style="word-wrap: break-word; min-height: 200px;">
                    <%= @referral.concerns %>
                  </div>
                </div>
            </div>

            <div class="row mt-4">
              <div class="col-sm-12 margin-bottom-11 career-pd-left-0">
                <p class="print-firefox-fontsize" style="font-size: 30px; font-weight: 800;">Extra Information</p>
              </div>


              <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                <p> Advertising</p>
                <div class="form-control">
                  <%= @referral.advertisement %>
                </div>
              </div>

              <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                <p> Advertising Additional Info</p>
                <div class="form-control">
                  <%= @referral.client_advertisement_other %>
                </div>
              </div>

              <div class="col-sm-12 margin-bottom-11 career-pd-left-0">
                <p>Additional Comment</p>
                <div class="form-control" style="word-wrap: break-word; min-height: 400px;">
                  <%= @referral.content %>
                </div>
              </div>


              </div>

            </div>

          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/admin_referrals/_medlegal.html.erb
<div class="container-fluid main-container">
  <div class="row print-firefox">
    <div class="col-sm-12" >
      <div class="" style="min-height: 900px;">
        <div class="container-fluid">
          <div class="row  print-firefox pdt-0" id='showReferral'>
            <div class="col-sm-12">
              <div class="row print-firefox" style="page-break-after: always;">
                <div class="col-sm-12 margin-bottom-11 career-pd-left-0 pt-1">
                  <p class="print-firefox-fontsize" style="font-size: 30px; font-weight: 800;">REFERRAL SOURCE INFORMATION</p>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>Category</p>
                  <div class="form-control">
                    <%= @referral.category %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>Lawyer Name </p>
                  <div class="form-control">
                    <%= @referral.rs_name %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>Lawyer Phone #</p>
                  <div class="form-control">
                    <%= @referral.rs_phone %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>Lawyer Fax #</p>
                  <div class="form-control">
                    <%= @referral.rs_fax %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>Lawyer Email</p>
                  <div class="form-control">
                    <%=  @referral.rs_email %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>Law Firm Name</p>
                  <div class="form-control">
                    <%=  @referral.rs_office_name %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>Law Office Address</p>
                  <div class="form-control">
                    <%=  @referral.rs_office_address %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>City</p>
                  <div class="form-control">
                    <%=  @referral.rs_city %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>Postal Code</p>
                  <div class="form-control">
                    <%=  @referral.rs_postal_code %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>Assistant/Paralegal Name</p>
                  <div class="form-control">
                    <%=  @referral.rs_assistant_name %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>Assistant/Paralegal phone</p>
                  <div class="form-control">
                    <%=  @referral.rs_assistant_phone %>
                  </div>
                </div>


                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>Assistant/Paralegal Email</p>
                  <div class="form-control">
                    <%=  @referral.rs_assistant_email %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 mgb-1">
                  <p>Do you represent Plaintiff or Defence?</p>
                  <div class="form-control">
                    <%=  @referral.rs_represents %>
                  </div>
                </div>

              </div>

              <div class="row mt-4 print-firefox" style="page-break-after: always;">
                <div class="col-sm-12 margin-bottom-11 career-pd-left-0">
                  <p class="print-firefox-fontsize" style="font-size: 30px; font-weight: 800;">CLIENT INFORMATION</p>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Client Name (include English name, where applicable)</p>
                  <div class="form-control">
                    <%= @referral.client_name %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Date of Birth</p>
                  <div class="form-control">
                  <% if @referral.client_birthday != nil %>
                    <%= (@referral.client_birthday).strftime("%B %d, %Y") %>
                  <% end %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Client Address </p>
                  <div class="form-control">
                    <%= @referral.client_address %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>City</p>
                  <div class="form-control">
                    <%=  @referral.client_city %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Postal Code</p>
                  <div class="form-control">
                    <%= @referral.client_postal_code %>
                  </div>
                </div>

               <div class='col-sm-6'></div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Claim No.</p>
                  <div class="form-control">
                    <%= @referral.client_file_number %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>File NO.</p>
                  <div class="form-control">
                    <%= @referral.client_sub_file_number %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Report Deadline</p>
                  <div class="form-control">
                  <% if @referral.client_report_deadline != nil %>
                      <%=  @referral.client_report_deadline.strftime("%B %d, %Y")%>
                    <% end %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Trial Date</p>
                  <div class="form-control">
                    <% if @referral.client_trial_date != nil %>
                      <%=  @referral.client_trial_date.strftime("%B %d, %Y")%>
                    <% end %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Trial Duration</p>
                  <div class="form-control">
                    <%= @referral.client_trial_duration_in_days %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Date Of Injury</p>
                  <div class="form-control">
                    <% if @referral.client_date_of_injury != nil %>
                      <%=  @referral.client_date_of_injury.strftime("%B %d, %Y")%>
                    <% end %>
                  </div>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 interpreter-required-result">
                  <p>Is an Interpreter Required?</p>
                  <div class="form-control">
                    <%=  @referral.client_interpreter_required %>
                  </div>
                </div>
                <div class="col-sm-6 margin-bottom-11 career-pd-left-0 interpreter-required-language" style="page-break-after: always;">
                  <div class='d-none'>
                    <p>Required Langauge</p>
                    <div class="form-control">
                      <%=  @referral.client_language_required %>
                    </div>
                  </div>
                </div>

                <div class="col-sm-12 margin-bottom-11 career-pd-left-0 print-show" style="display: none;">
                  <p class="print-firefox-fontsize" style="font-size: 30px; font-weight: 800;">CLIENT INFORMATION</p>
                </div>

                <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p>Client Gender</p>
                  <div class="form-control">
                    <%= @referral.client_sex %>
                  </div>
                </div>

               <!-- <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                  <p> Client Gender(other)</p>
                  <div class="form-control">
                    <%#= @referral.client_sex_other %>
                  </div>
                </div> -->

                <div class="col-sm-12 margin-bottom-11 career-pd-left-0">
                  <p>Will a rebuttal report be required, or only a verbal opinion/aid with trial prep?</p>
                  <div class="form-control">
                    <%=  @referral.client_rebuttal_needed %>
                  </div>
                </div>

                <div class="col-sm-12 margin-bottom-11 career-pd-left-0">
                  <p>Please provide a list of reports to be reviewed, along with their corresponding clinicians?</p>
                  <div class="form-control", style="word-wrap: break-word; min-height: 400px;">
                    <%=  @referral.concerns %>
                  </div>
                </div>

            </div>

            <div class="row mt-4">
              <div class="col-sm-12 margin-bottom-11 career-pd-left-0">
                <p class="print-firefox-fontsize" style="font-size: 30px; font-weight: 800;">Extra Information</p>
              </div>


              <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                <p>Advertising</p>
                <div class="form-control">
                  <%= @referral.advertisement %>
                </div>
              </div>

              <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
                <p>Advertising Additional Info</p>
                <div class="form-control">
                  <%= @referral.client_advertisement_other %>
                </div>
              </div>

              <div class="col-sm-12 margin-bottom-11 career-pd-left-0">
                <p>Additional Comment</p>
                <div class="form-control" style="word-wrap: break-word; min-height: 400px;">
                  <%= @referral.content %>
                </div>
              </div>


              </div>

            </div>

          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/admin_referrals/index.html.erb
<div class="admin-nav">
  <a class="navbar-brand" href="#"><%= image_tag("refunction_nav_logo.svg", class:"admin-logo") %>
  </a>
    <%= link_to "Log Out", logout_path, class:"btn admin-log-out-btn", method: :delete %>
</div>

<div class="container-fluid">
  <div class="row">

    <%= render 'layouts/admin_nav' %>


    <div class="admin-body col-sm-10">
      <div class="admin-team-search-bar" style="min-height: 900px;">
        <div class="container-fluid">
          <div class="row">
            <div class="search-top col-sm-12">
              <p>Referrals</p>
            </div>
          </div>
          <div class="row admin-search-padding">
            <div class="col-sm-12">
              <div class="row">
                <table class="table table-striped" id="referralTable">
                  <thead>
                    <tr>
                      <th scope="col">Date</th>
                      <th scope="col">Conf No.</th>
                      <th scope="col">Type</th>
                      <th scope="col">Name</th>
                      <th scope="col">Claim/Policy No.</th>
                      <th scope="col">File/Client ID No.</th>
                      <th scope="col">Company</th>
                      <th scope="col">Advertisement</th>
                      <th scope="col">View</th>
                      <th scope="col">Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @referrals.each do |f| %>
                      <tr>
                        <th scope="row"><%= f.created_at.to_date %></th>
                        <td><%= f.public_uid %></td>
                        <td><%= f.referral_form_type %></td>
                        <td><%= f.rs_name %></td>
                        <td><%= f.client_file_number %></td>
                        <td><%= f.client_sub_file_number %></td>
                        <td><%= f.rs_office_name %></td> <!-- This is "Category" -->

                        <td><%= f.advertisement%></td>
                        <td><%= link_to "Show", admin_referral_path(f.public_uid) %></td>
                        <td><%= link_to "Delete", admin_referral_path(f.public_uid), method: :delete, data: {confirm: 'Are you sure?'} %></td>
                      </tr>
                    <% end %>

                  </tbody>
              </table>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/admin_referrals/show.html.erb
<div class='row'>
  <div class='col-md-12'>
    <button id="printPageButton", class="referral_print_button", onClick="window.print();">Print</button>
    <h2 class='header-confirmation-code'>Confirmation No. <%= @referral.public_uid %></h2>
  </div>
</div>

<% if @referral.referral_form_type == "employer" %>
  <%= render "employee" %>
<%  else  %>
  <%= render "medlegal" %>
<% end %>