config/routes.rb
Rails.application.routes.draw do


  # get 'users/new'

  get 'home/index'
  get 'faq', to: "home#faq", as: 'faq'
  resources :services
  get '/service_index_admin', to: 'services#index_admin'
  get '/functional_evaluation', to: 'services#functional_evaluation'
  get '/cost_of_future_care', to: 'services#cost_of_future_care'
  get '/medical_legal_consultation', to: 'services#medical_legal_consultation'
  get '/community_rehabilitation', to: 'services#community_rehabilitation'
  get '/physiotherapy', to: 'services#physiotherapy'
  get '/functional_conditioning', to: 'services#functional_conditioning'
  get '/interdisciplinary_rehabilitation', to: 'services#interdisciplinary_rehabilitation'
  get '/job_demands_analyses', to: 'services#job_demands_analyses'
  get '/ergononmic_risk_factor_analyses', to: 'services#ergononmic_risk_factor_analyses'
  get '/clinical_counselling_services', to: 'services#clinical_counselling_services'
  get '/psychology_assessment', to: 'services#psychology_assessment'
  resources :about_us, only: [:index]
  resources :testimonials
  resources :careers, only: [:index, :show]
  resources :contacts
  get '/surrey', to: "contacts#surrey"
  get '/vancouver', to: "contacts#vancouver"
  get '/coquitlam', to: "contacts#coquitlam"
  get '/abbotsford', to: "contacts#abbotsford"
  get '/victoria', to: "contacts#victoria"
  get '/nanaimo', to: "contacts#nanaimo"
  get '/kelowna', to: "contacts#kelowna"

  resources :admin_dashboard, only: [:index]
  resources :our_teams
  get '/office_administration', to: "our_teams#office_administration"
  get '/occupational_therapists', to: "our_teams#occupational_therapists"
  get '/physiotherapists', to: "our_teams#physiotherapists"
  get '/kinesiologist', to: "our_teams#kinesiologist"
  get '/memorials', to: "our_teams#memorial"
  get '/psychology', to: "our_teams#psychology"
  get '/psychiatrist', to: "our_teams#psychiatrist"
  get '/counsellors', to: "our_teams#counsellors"
  get '/medlegal', to: "referrals#medlegal"
  get '/employer', to: "referrals#employer"
  get '/covid_19', to: "coronas#index"
  resources :users
  resources :admin_teams
  get '/index_original', to: "admin_teams#index_original"
  post 'team_archive/:id', to: "admin_teams#archive", as:'team_archive'
  resources :members
  resources :admin_careers
  resources :admin_testimonials
  resources :admin_enquiries
  resources :job_applications

  post 'testimonial_archive/:id', to: "admin_testimonials#archive", as:'testimonial_archive'
  post 'careers_archive/:id', to: "admin_careers#archive", as:'career_archive'

  resources :admin_enquiries
  resources :referrals

  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :admin_referrals
  resources :info_referrals
  resources :locations


  get '*path' => redirect('/')

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_career.rb
class AdminCareer < ApplicationRecord
  mount_uploader :career, ImageUploader
  validates :title, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :career, presence: true

end

app/models/admin_enquiry.rb
class AdminEnquiry < ApplicationRecord
end

app/models/admin_referral.rb
class AdminReferral < ApplicationRecord
  require 'sendgrid-ruby'
  include SendGrid
  # validates :client_name, presence: true
  # validates :name, presence: true
  # validates :company, presence: true
  # validates :phone, presence: true
  # validates :email, presence: true
  # validates :client_phone, presence: true
  # validates :advertisement, presence: true

  generate_public_uid
  
  def self.find_param(param)
    find_by! public_uid: param.split('-').first
  end

  after_create :add_categorizer_to_confirmation_code

  private

  def add_categorizer_to_confirmation_code
    loop do
      public_uid = self.public_uid
      public_uid = public_uid.prepend('M') if self.referral_form_type == 'medlegal'
      public_uid = public_uid.prepend('E') if self.referral_form_type == 'employer'
      break unless AdminReferral.exists?(public_uid: public_uid)
    end
    self.update_column(:public_uid, public_uid)
  end

  def send_mail_to_creator
    from = Email.new(email: 'test@example.com')
    to = Email.new(email: 'test@example.com')
    subject = 'Sending with SendGrid is Fun'
    content = Content.new(type: 'text/plain', value: 'and easy to do anywhere, even with Ruby')
    mail = Mail.new(from, subject, to, content)

    sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
    response = sg.client.mail._('send').post(request_body: mail.to_json)
  end
end

app/models/admin_team.rb
class AdminTeam < ApplicationRecord
  belongs_to :job_category
  mount_uploader :image, ImageUploader
  mount_uploader :resume, ResumeUploader

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :image, presence: true

  def memorial?
    state = false
    memorial_category_id = JobCategory.find_by(title: 'Memorial').id
    state = true if self.job_category_id == memorial_category_id
    state
  end
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  mount_uploader :resume, ApplyUploader
end

app/models/job_category.rb
class JobCategory < ApplicationRecord
  has_many :admin_teams
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  mount_uploader :image, ImageUploader
  
end

app/models/service.rb
class Service < ApplicationRecord
  mount_uploader :picture, ServiceImageUploader

  validates :title, presence: true
  validates :picture, presence: true
  validates :content, presence: true
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true

  has_secure_password
end

app/controllers/admin_careers_controller.rb
class AdminCareersController < ApplicationController
  before_action :logged_in_check
  
  def index
    @admin_careers_published = AdminCareer.where(published: true)
    @admin_careers_archived = AdminCareer.where(published: false)
  end

  def show
    @admin_career = AdminCareer.find(params[:id])
  end

  def new
    @admin_career = AdminCareer.new
  end

  def create
    @admin_career = AdminCareer.new(admin_career_params)
    if params[:commit] == "Save & Publish"
      @admin_career.published = true
    else
      @admin_career.published = false
    end
    if @admin_career.save
      redirect_to admin_careers_path
    else
      render 'new'
    end
  end

  def edit
    @admin_career = AdminCareer.find(params[:id])
  end

  def archive
    @admin_career = AdminCareer.find(params[:id])
    if @admin_career.published == true
      @admin_career.published = false
    else
      @admin_career.published = true
    end
    @admin_career.save
    redirect_to admin_careers_path
  end

  def update
    @admin_career = AdminCareer.find(params[:id])
    if @admin_career.update(admin_career_params)
      redirect_to admin_careers_path
    else
      render 'edit'
    end
  end

  def destroy
    @admin_career = AdminCareer.find(params[:id])
    @admin_career.destroy
    redirect_to admin_careers_path
  end

  private

  def admin_career_params
    params.require(:admin_career).permit(:title,:location,:description,:preview_description,:career,:posting_position,:type_of_job)
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/admin_careers_helper.rb
module AdminCareersHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/coronas_helper.rb
module CoronasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_careers/_form.html.erb
<% if @admin_career.errors.any? %>
  <div id="error_explanation">
   <h2><%= pluralize(@admin_career.errors.count, "error") %> prohibited this career from being saved:</h2>

   <ul>
   <% @admin_career.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
  </div>
<% end %>

<%= form_for(@admin_career) do |f| %>
<div class="container card-inner-padding">
  <div class="row justify-content-between mg-left card-margin-bottom">
    <div>

      <%= f.label :career %><br>
      <%= f.file_field :career,  onchange:"readURL(this)"%>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
         <img id="img_prev" src="#" alt="Image Preview" />
    </div>

    <div class="col-sm-6">
      <div class="row">
        <div class="col-sm-12 margin-bottom-11" style="padding-left: 0px;">
          <%= f.text_field :title, class:"form-control input-box", placeholder: "Title" %>
        </div>
        <div class="col-sm-12 margin-bottom-11" style="padding-left: 0px;">
          <%= f.text_field :location, class:"form-control input-box", placeholder: "Location" %>
        </div>
        <!-- <div class="col-sm-12 margin-bottom-11" style="padding-left: 0px;">
          <#%= f.text_field :posting_position, class:"form-control input-box", placeholder: "Position tilte" %>
        </div> -->
        <div class="col-sm-12 margin-bottom-11" style="padding-left: 0px;">
          <%= f.text_field :type_of_job, class:"form-control input-box", placeholder: "Full Time or Part Time" %>
        </div>
      </div>
    </div>
    <div class="col-sm-12 card-margin-top">
      <%= f.text_area :preview_description, :class => "form-control input-box", :rows => 5, :cols => 30 %>
    </div>
    <div class="col-sm-12 card-margin-top">
      <%= f.text_area :description, :class => "tinymce", :rows => 40, :cols => 30 %>
      <%= tinymce %>
    </div>
    <div class="col-sm-12 card-margin-top">
      <%= f.submit "Save", class:"admin-button-blue" %>
      <%= f.submit "Save & Publish", class:"admin-button-gray", value: "Save & Publish" %>
    </div>
  </div>
<% end %>

app/views/admin_careers/edit.html.erb
<div class="admin-nav">
  <a class="navbar-brand" href="#"><%= image_tag("refunction_nav_logo.svg", class:"admin-logo") %>
  </a>
  <%= link_to "Log Out", logout_path, class:"btn admin-log-out-btn", method: :delete %>
</div>

<div class="container-fluid">
  <div class="row">
    <%= render 'layouts/admin_nav' %>

    <div class="admin-body col-sm-10">
      <div class="admin-card">
        <div class="container-fluid">
          <div class="row">
            <div class="search-top col-sm-12 pd-top-10">
              <p>Edit Careers</p>
            </div>
          </div>
        </div>
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>


<!-- Assume jQuery is loaded -->
    <script>
      function readURL(input) {
        if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
            $('#img_prev')
              .attr('src', e.target.result)
              .width(300)
              .height(250);
          };

          reader.readAsDataURL(input.files[0]);
        }
      }
    </script>

app/views/admin_careers/index.html.erb
<div class="admin-nav">
  <a class="navbar-brand" href="#"><%= image_tag("refunction_nav_logo.svg", class:"admin-logo") %>
  </a>
    <%= link_to "Log Out", logout_path, class:"btn admin-log-out-btn", method: :delete %>
</div>

<div class="container-fluid">
  <div class="row">

    <%= render 'layouts/admin_nav' %>


    <div class="admin-body col-sm-10">
      <div class="admin-team-search-bar">
        <div class="container-fluid">
          <div class="row">
            <div class="search-top col-sm-12">
              <p>Published Job Posting</p>
            </div>
          </div>
          <div class="row admin-search-padding">
            <div class="col-sm-12">
              <div class="row">
                <div class="offset-sm-9 col-sm-3">
                    <a href="/admin_careers/new"><div class="admin-search-button mg-bottom"> Add New</div></a>
                </div>
                <div class="col-sm-12">
                  <div class="row">
                    <% @admin_careers_published.each do |f| %>
                    <div class="col-sm-6 mg-bottom">
                      <div class="careers-box">
                        <div class="row">
                          <div class="col-sm-4 careers-image" style="padding-left: 0px; padding-right: 0px;">
                            <!-- <#%= image_tag("refunction_home_services.png") %> -->
                            <%= image_tag f.career.portrait.url %>
                          </div>
                          <div class="col-sm-8 reset" style="padding-left: 5px;padding-right: 0px;">
                            <div class="card-body reset" style="padding-top: 0px;padding-bottom: 0px;padding-left: 0px;padding-right: 0px;">
                              <div>
                                <span class="careers-posting-date">Posted June 30, 2018</span>
                              </div>
                              <div>
                                <span class="careers-posting-title bold"><%= f.title %></span>
                              </div>

                              <div class="highlight-thin careers-posting-highlight"></div>
                              <p class="card-text text-pd-right" style="font-size: 0.7em; margin-bottom: 3px;"><%= f.preview_description.truncate(200) %>
                              </p>

                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="admin-staff-image-button">
                        <div class="btn btn-primary font-white">
                          <%= link_to "Edit", edit_admin_career_path(f) %>
                        </div>
                        <div class="btn btn-success font-white">
                          <%= link_to "Archive", career_archive_path(f), method: :post %>
                        </div>
                        <div class="btn btn-danger font-white">
                          <%= link_to "Delete", admin_career_path(f), method: :delete, data: {confirm: "Are you sure?"} %>
                        </div>
                      </div>
                    </div>
                    <% end %>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>




      <div class="admin-team-search-bar" style="min-height: 400px;">
        <div class="container-fluid">
          <div class="row">
            <div class="search-top col-sm-12">
              <p>Archived Job Posting</p>
            </div>
          </div>
          <div class="row admin-search-padding">
            <div class="col-sm-12">
              <div class="row">
                <div class="col-sm-12">
                  <div class="row">

                    <% @admin_careers_archived.each do |f| %>
                    <div class="col-sm-6 mg-bottom">
                      <div class="careers-box">
                        <div class="row">
                          <div class="col-sm-4 careers-image" style="padding-left: 0px; padding-right: 0px;">
                            <%= image_tag f.career.portrait.url %>
                          </div>
                          <div class="col-sm-8 reset" style="padding-left: 5px;padding-right: 0px;">
                            <div class="card-body reset" style="padding-top: 0px;padding-bottom: 0px;padding-left: 0px;padding-right: 0px;">
                              <div>
                                <span class="careers-posting-date"><%= f.created_at.strftime("%m/%d/%Y") %></span>
                              </div>
                              <div>
                                <span class="careers-posting-title bold"><%= f.posting_position %></span>
                              </div>

                              <div class="highlight-thin careers-posting-highlight"></div>
                              <p class="card-text text-pd-right" style="font-size: 0.7em; margin-bottom: 3px;"><%= f.preview_description %>
                              </p>

                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="admin-staff-image-button">
                        <div class="btn btn-primary font-white">
                          <%= link_to "Edit", edit_admin_career_path(f) %>
                        </div>
                        <div class="btn btn-success font-white">
                          <%= link_to "Publish", career_archive_path(f), method: :post %>
                        </div>
                        <div class="btn btn-danger font-white">
                          <%= link_to "Delete", admin_career_path(f), method: :delete, data: {confirm: "Are you sure?"} %>
                        </div>
                      </div>
                    </div>
                    <% end %>



                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/admin_careers/new.html.erb
<div class="admin-nav">
  <a class="navbar-brand" href="#"><%= image_tag("refunction_nav_logo.svg", class:"admin-logo") %>
  </a>
    <%= link_to "Log Out", logout_path, class:"btn admin-log-out-btn", method: :delete %>
</div>

<div class="container-fluid">
  <div class="row">
    <%= render 'layouts/admin_nav' %>

    <div class="admin-body col-sm-10">
      <div class="admin-card">
        <div class="container-fluid">
          <div class="row">
            <div class="search-top col-sm-12 pd-top-10">
              <p>New Careers</p>
            </div>
          </div>
        </div>
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>


<!-- Assume jQuery is loaded -->
    <script>
      function readURL(input) {
        if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
            $('#img_prev')
              .attr('src', e.target.result)
              .width(300)
              .height(250);
          };

          reader.readAsDataURL(input.files[0]);
        }
      }
    </script>

app/views/admin_careers/show.html.erb
<%= render "layouts/nav" %>
<%= render "layouts/banner_top_deco" %>
<%= render "layouts/breadcrumb" %>

<div class="why_work_with_us pages-card-padding">
  <div class="container">
    <div class="row">

      <div class="col-sm-3">
        <div class="row justify-content-between">
          <div class="list_of_services_box">
            <h5>Learn about our services</h5>
            <div class="highlight"></div>
            <ul>
              <li><span class="current-listing-header">Kinesiologist Position</span>
                <span class="current-listing-header-sub">Lower Mainland & Nanaimo</span>
              </li>
              <li><span class="current-listing-header">Occupational Therapist</span>
                <span class="current-listing-header-sub">Lower Mainland</span>
              </li>
              <li><span class="current-listing-header">Occupational Therapist</span>
                <span class="current-listing-header-sub">Nanaimo</span>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="offset-sm-1 col-sm-8">

        <div class="row">
          <p class="show-header"> <%= @admin_career.title %> - <%= @admin_career.location %></p>
          <p class="show-font">
            <%= raw(@admin_career.description) %>
          </p>
        </div>


        <div class="row careers-featured-opening-empty">

        </div>

        <div class="row">
            <p style="padding-top: 10px; font-weight: 700;">Send your information and CV</p>
        </div>
        <div class="row">
          <div class="col-sm-6 margin-bottom-11 career-pd-left-0">
            <input type="text" class="form-control input-box" placeholder="First name">
          </div>
          <div class="col-sm-6 margin-bottom-11 career-pd-right-0" >
            <input type="text" class="form-control input-box" placeholder="Last name">
          </div>
          <div class="col-sm-6 margin-bottom-11 career-pd-left-0" >
            <input type="text" class="form-control input-box" placeholder="Email">
          </div>
          <div class="col-sm-6 margin-bottom-11 career-pd-right-0" >
            <input type="text" class="form-control input-box" placeholder="Phone">
          </div>
          <div class="form-group col-sm-12 career-pd-left-0 career-pd-right-0" >
            <textarea class="form-control" style="height: 339px; width: 100%;" id="exampleFormControlTextarea1" placeholder="Leave us a message"></textarea>
          </div>
        </div>

          <div class="row">
            <div class="col-3" style="padding-left: 0px;">
              <button class="cta-see-team">Upload CV</button>
            </div>
            <div class="col-3">
              <button class="cta-see-team" style="width: 181px;">Submit</button>
            </div>
          </div>

      </div>

    </div>
  </div>
</div>

<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>