config/routes.rb
Rails.application.routes.draw do


  # get 'users/new'

  get 'home/index'
  get 'faq', to: "home#faq", as: 'faq'
  resources :services
  get '/service_index_admin', to: 'services#index_admin'
  get '/functional_evaluation', to: 'services#functional_evaluation'
  get '/cost_of_future_care', to: 'services#cost_of_future_care'
  get '/medical_legal_consultation', to: 'services#medical_legal_consultation'
  get '/community_rehabilitation', to: 'services#community_rehabilitation'
  get '/physiotherapy', to: 'services#physiotherapy'
  get '/functional_conditioning', to: 'services#functional_conditioning'
  get '/interdisciplinary_rehabilitation', to: 'services#interdisciplinary_rehabilitation'
  get '/job_demands_analyses', to: 'services#job_demands_analyses'
  get '/ergononmic_risk_factor_analyses', to: 'services#ergononmic_risk_factor_analyses'
  get '/clinical_counselling_services', to: 'services#clinical_counselling_services'
  get '/psychology_assessment', to: 'services#psychology_assessment'
  resources :about_us, only: [:index]
  resources :testimonials
  resources :careers, only: [:index, :show]
  resources :contacts
  get '/surrey', to: "contacts#surrey"
  get '/vancouver', to: "contacts#vancouver"
  get '/coquitlam', to: "contacts#coquitlam"
  get '/abbotsford', to: "contacts#abbotsford"
  get '/victoria', to: "contacts#victoria"
  get '/nanaimo', to: "contacts#nanaimo"
  get '/kelowna', to: "contacts#kelowna"

  resources :admin_dashboard, only: [:index]
  resources :our_teams
  get '/office_administration', to: "our_teams#office_administration"
  get '/occupational_therapists', to: "our_teams#occupational_therapists"
  get '/physiotherapists', to: "our_teams#physiotherapists"
  get '/kinesiologist', to: "our_teams#kinesiologist"
  get '/memorials', to: "our_teams#memorial"
  get '/psychology', to: "our_teams#psychology"
  get '/psychiatrist', to: "our_teams#psychiatrist"
  get '/counsellors', to: "our_teams#counsellors"
  get '/medlegal', to: "referrals#medlegal"
  get '/employer', to: "referrals#employer"
  get '/covid_19', to: "coronas#index"
  resources :users
  resources :admin_teams
  get '/index_original', to: "admin_teams#index_original"
  post 'team_archive/:id', to: "admin_teams#archive", as:'team_archive'
  resources :members
  resources :admin_careers
  resources :admin_testimonials
  resources :admin_enquiries
  resources :job_applications

  post 'testimonial_archive/:id', to: "admin_testimonials#archive", as:'testimonial_archive'
  post 'careers_archive/:id', to: "admin_careers#archive", as:'career_archive'

  resources :admin_enquiries
  resources :referrals

  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :admin_referrals
  resources :info_referrals
  resources :locations


  get '*path' => redirect('/')

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/our_teams_controller.rb
class OurTeamsController < ApplicationController
  MEMORIAL_JOB_CATEGORY_ID = JobCategory.find_by(title:'Memorial').id

  def index
    @search = AdminTeam.search(params[:q])
    @teams = @search.result
    @memorial_teams = @teams.where(published: true).where(job_category_id: MEMORIAL_JOB_CATEGORY_ID)
    @memorial_teams = @memorial_teams.sort_by {|x| x.first_name}
    @teams = @teams.where(published: true).where.not(job_category_id: MEMORIAL_JOB_CATEGORY_ID)
    @teams = @teams.sort_by {|x| x.first_name}
    @admin_enquiry = AdminEnquiry.new
  end

  def show
  end

  def office_administration
    @search = AdminTeam.search(params[:q])
    @teams = AdminTeam.where(job_category_id: 1)
    @teams = @teams.where(published: true)
    @teams = @teams.sort_by {|x| x.first_name}
    @admin_enquiry = AdminEnquiry.new
  end

  def occupational_therapists
      @search = AdminTeam.search(params[:q])
    @teams = AdminTeam.where(job_category_id: 2)
    @teams = @teams.where(published: true)
    @teams = @teams.sort_by {|x| x.first_name}
    @admin_enquiry = AdminEnquiry.new
  end

  def physiotherapists
    @search = AdminTeam.search(params[:q])
    @teams = AdminTeam.where(job_category_id: 3)
    @teams = @teams.where(published: true)
    @teams = @teams.sort_by {|x| x.first_name}
    @admin_enquiry = AdminEnquiry.new
  end

  def kinesiologist
    @search = AdminTeam.search(params[:q])
    @teams = AdminTeam.where(job_category_id: 4)
    @teams = @teams.where(published: true)
    @teams = @teams.sort_by {|x| x.first_name}
    @admin_enquiry = AdminEnquiry.new
  end

  def psychology
    @search = AdminTeam.search(params[:q])
    @teams = AdminTeam.where(job_category_id: 5)
    @teams = @teams.where(published: true)
    @teams = @teams.sort_by {|x| x.first_name}
    @admin_enquiry = AdminEnquiry.new
  end

  def counsellors
    @search = AdminTeam.search(params[:q])
    @teams = AdminTeam.where(job_category_id: 6)
    @teams = @teams.where(published: true)
    @teams = @teams.sort_by {|x| x.first_name}
    @admin_enquiry = AdminEnquiry.new
  end

  def psychiatrist
    @search = AdminTeam.search(params[:q])
    @teams = AdminTeam.where(job_category_id: 7)
    @teams = @teams.where(published: true)
    @teams = @teams.sort_by {|x| x.first_name}
    @admin_enquiry = AdminEnquiry.new
  end

  def memorial

    @search = AdminTeam.search(params[:q])
    @teams = AdminTeam.where(job_category_id: MEMORIAL_JOB_CATEGORY_ID)
    @teams = @teams.where(published: true)
    @teams = @teams.sort_by {|x| x.first_name}
    @admin_enquiry = AdminEnquiry.new
  end
end

app/helpers/our_teams_helper.rb
module OurTeamsHelper
end

app/views/our_teams/_filter.html.erb
<div class="bread-crumb-border mb-margin-top-40">
  <div class="container">
    <div class="row">
      <div class="bread-crumb col-sm-12">
        <div class="row justify-content-between">

          <div class="col-lg-12 col-xl-6">
            <div id="custom-search-input">
                  <%= search_form_for @search, html: { class: "input-group col-md-12", style: "height: 37px; padding-right: 0px;" } do |f| %>

                    <%= f.text_field :first_name_cont, class:"form-control input-lg" %>
                    <%= f.submit "Search", class:"btn btn-info btn-md", style:"    height: 37px;"%>
                  <% end %>


                    <!-- <input type="text" class="form-control input-lg" placeholder="Search" />
                    <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="button">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span> -->

            </div>
          </div>

          <div class="col-lg-12 col-xl-6" style="padding-right: 0px;">
            <span style="margin-right: 24px;">Filter by Department: </span>
              <select onChange="window.location.href=this.value" class="input-box" style="height: 48px; width: 265px;">
                <option value="/office_administration">Departments</option>
                <option value="/occupational_therapists">Occupational Therapists</option>
                <option value="/office_administration">Office & Administration</option>
                <option value="/physiotherapists">Physiotherapists</option>
                <option value="/psychology">Psychologists</option>
                <option value="/psychiatrist">Psychiatrist</option>
                <option value="/kinesiologist">Kinesiologists</option>
                <option value="/counsellors">Counsellors</option>
                <option value="/memorials">Memorials</option>
                <option value="/our_teams">All</option>
              </select>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/our_teams/_memorials.html.erb
<div class="row">
  <% @teams.each do |f| %>
  <div class="col-sm-12 col-md-12 col-lg-6 mg-bt-20 teams_card">
    <div class="card">
      <div>
         <%= image_tag f.image.url, class:"img-fluid border-color min-height-profile" %>
      </div>
      <div class="card-body" style="min-height: 210px;">
        <span class="font-lb bold"><%= f.first_name %> <%= f.last_name %></span>
        <p class="card-text font-size-sm"><%= raw(f.bio) %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/our_teams/_side_link.html.erb
<div class="col-sm-3 border-right tablet-dp-none mb-dp-none">
  <div class="row align-items-center">
    <ul class="our-team-dp-list">
      <li><span class="dp-list-header">Departments</span></li>
      <li><a href="/occupational_therapists">Occupational Therapists</a></li>
      <li><a href="/office_administration">Office & Administration</a></li>
      <li><a href="/physiotherapists">Physiotherapists</a></li>
      <li><a href="/psychology">Psychologists</a></li>
      <li><a href="/psychiatrist">Psychiatrist</a></li>
      <li><a href="/kinesiologist">Kinesiologists</a></li>
      <li><a href="/counsellors">Counsellors</a></li>
      <li><a href="/our_teams">All</a></li>
      <br><br>
      <li><a href="/memorials">In Memoriam</a></li>
    </ul>
  </div>


 
</div>

app/views/our_teams/_teams.html.erb
<div class="row">
  <% @teams.each do |f| %>
  <div class="col-sm-12 col-md-12 col-lg-6 col-xl-4 mg-bt-20 teams_card">
    <div class="card">
      <div class="our-teams-card-img">
         <%= image_tag f.image.url, class:"img-fluid border-color min-height-profile" %>
      </div>
      <div class="card-body" style="min-height: 210px;">
        <span class="font-lb bold"><%= f.first_name %> <%= f.last_name %></span>
        <p class="card-text font-size-sm"><%= f.title %></p>
        <p class="card-text font-size-sm" style="margin-bottom: 3px;"><%= f.occupation %></p>
        <p class="card-text font-size-sm"><%= f.second_title %></p>
        <%= link_to "Learn More", admin_team_path(f) %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/our_teams/counsellors.html.erb
<%= render "layouts/nav" %>
<div class="banner_top_deco">
  <div class="banner-top-deco-inner-text">
    <div class="container" style="padding-bottom: 10px;">
      <div class="row mb-dp-none">
        <div class="banner-top-deco-header col-sm-12">
          Our Team
        </div>
        <div class="banner-top-deco-sub col-sm-12">
  
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'filter' %>


<div class="our-teams pages-card-padding">
  <div class="container">
    <div class="row">
        <%= render 'side_link' %>
      <div class="col-sm-9">
        <p class="about-us-header">Counsellors</p>
        <%= render 'teams' %>
      </div>

    </div>
  </div>
</div>
<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>

app/views/our_teams/index.html.erb
<%= render "layouts/nav" %>
<div class="banner_top_deco">
  <div class="banner-top-deco-inner-text">
    <div class="container" style="padding-bottom: 10px;">
      <div class="row mb-dp-none">
        <div class="banner-top-deco-header col-sm-12">
          Our Team
        </div>
        <div class="banner-top-deco-sub col-sm-12">

        </div>
      </div>
    </div>
  </div>
</div>


<%= render 'filter' %>


<div class="our-teams pages-card-padding">

  <div class="container">
    <div class="row">
      <%= render 'side_link' %>
      <div class="col-sm-12 col-md-12 col-lg-12 col-xl-9">
        <p class="about-us-header">Re:Function Team</p>
        <div class="row">
          <% @teams.each do |f| %>
          <div class="col-sm-12 col-md-12 col-lg-6 col-xl-4 mg-bt-20 mobile-our-team-card teams_card">
            <div class="card">
              <div class="our-teams-card-img">
                  <%= image_tag f.image.url, class:"img-fluid border-color min-height-profile"%>
              </div>
        
              <div class="card-body" style="min-height: 220px;">
                <span class="font-lb bold"><%= f.first_name %> <%= f.last_name %></span>
                <p class="card-text font-size-sm"><%= f.title %></p>
                <p class="card-text font-size-sm" style="margin-bottom: 3px;"><%= f.occupation %></p>
                <p class="card-text font-size-sm"><%= f.second_title %></p>
                <%= link_to "Learn More", admin_team_path(f) %>
              </div>
            </div>
          </div>
          <% end %>



        </div>
      </div>

    </div>
  </div>

  <div class="container mt-5">
    <div class="row">
      <div class="col-sm-3 border-right tablet-dp-none mb-dp-none">
      </div>
      <div class="col-sm-12 col-md-12 col-lg-12 col-xl-9">
        <p class="about-us-header">In Memoriam</p>
        <div class="row">
          <% @memorial_teams.each do |f| %>
          <div class="col-sm-12 col-md-12 col-lg-6 col-xl-4 mg-bt-20 mobile-our-team-card teams_card">
            <div class="card">
              <div class="our-teams-card-img">
                  <%= image_tag f.image.url, class:"img-fluid border-color min-height-profile"%>
              </div>
        
              <div class="card-body" style="min-height: 220px;">
                <span class="font-lb bold"><%= f.first_name %> <%= f.last_name %></span>
                <p class="card-text font-size-sm"><%= f.title %></p>
                <p class="card-text font-size-sm" style="margin-bottom: 3px;"><%= f.occupation %></p>
                <p class="card-text font-size-sm"><%= f.second_title %></p>
                <%= link_to "Learn More", admin_team_path(f) %>
              </div>
            </div>
          </div>
          <% end %>



        </div>
      </div>

    </div>
  </div>

</div>
<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>

app/views/our_teams/kinesiologist.html.erb
<%= render "layouts/nav" %>
<div class="banner_top_deco">
  <div class="banner-top-deco-inner-text">
    <div class="container" style="padding-bottom: 10px;">
      <div class="row mb-dp-none">
        <div class="banner-top-deco-header col-sm-12">
          Our Team
        </div>
        <div class="banner-top-deco-sub col-sm-12">
          
        </div>
      </div>
    </div>
  </div>
</div>


<%= render 'filter' %>


<div class="our-teams pages-card-padding">
  <div class="container">
    <div class="row">
        <%= render 'side_link' %>
      <div class="col-sm-9">
        <p class="about-us-header">Kinesiologists</p>
        <%= render 'teams' %>
      </div>

    </div>
  </div>
</div>
<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>

app/views/our_teams/memorial.html.erb
<%= render "layouts/nav" %>
<div class="banner_top_deco">
  <div class="banner-top-deco-inner-text">
    <div class="container" style="padding-bottom: 10px;">
      <div class="row mb-dp-none">
        <div class="banner-top-deco-header col-sm-12">
          Our Team
        </div>
        <div class="banner-top-deco-sub col-sm-12">

        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'filter' %>


<div class="our-teams pages-card-padding">
  <div class="container">
    <div class="row">
        <%= render 'side_link' %>
      <div class="col-sm-9">
        <p class="about-us-header">Memorial</p>
        <%= render 'memorials' %>
      </div>

    </div>
  </div>
</div>
<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>

app/views/our_teams/occupational_therapists.html.erb
<%= render "layouts/nav" %>
<div class="banner_top_deco">
  <div class="banner-top-deco-inner-text">
    <div class="container" style="padding-bottom: 10px;">
      <div class="row mb-dp-none">
        <div class="banner-top-deco-header col-sm-12">
          Our Team
        </div>
        <div class="banner-top-deco-sub col-sm-12">
          
        </div>
      </div>
    </div>
  </div>
</div>


<%= render 'filter' %>


<div class="our-teams pages-card-padding">
  <div class="container">
    <div class="row">
        <%= render 'side_link' %>
      <div class="col-sm-9">
        <p class="about-us-header">Occupational Therapists</p>
        <%= render 'teams' %>
      </div>

    </div>
  </div>
</div>
<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>

app/views/our_teams/office_administration.html.erb
<%= render "layouts/nav" %>
<div class="banner_top_deco">
  <div class="banner-top-deco-inner-text">
    <div class="container" style="padding-bottom: 10px;">
      <div class="row mb-dp-none">
        <div class="banner-top-deco-header col-sm-12">
          Our Team
        </div>
        <div class="banner-top-deco-sub col-sm-12">
          
        </div>
      </div>
    </div>
  </div>
</div>


<%= render 'filter' %>


<div class="our-teams pages-card-padding">
  <div class="container">
    <div class="row">
        <%= render 'side_link' %>
      <div class="col-sm-9">
        <p class="about-us-header">Office & Administration Staff</p>
        <%= render 'teams' %>
      </div>

    </div>
  </div>
</div>

<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>

app/views/our_teams/physiotherapists.html.erb
<%= render "layouts/nav" %>
<div class="banner_top_deco">
  <div class="banner-top-deco-inner-text">
    <div class="container" style="padding-bottom: 10px;">
      <div class="row mb-dp-none">
        <div class="banner-top-deco-header col-sm-12">
          Our Team
        </div>
        <div class="banner-top-deco-sub col-sm-12">
          
        </div>
      </div>
    </div>
  </div>
</div>


<%= render 'filter' %>


<div class="our-teams pages-card-padding">
  <div class="container">
    <div class="row">
        <%= render 'side_link' %>
      <div class="col-sm-9">
        <p class="about-us-header">Physiotherapists</p>
        <%= render 'teams' %>
      </div>

    </div>
  </div>
</div>
<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>

app/views/our_teams/psychiatrist.html.erb
<%= render "layouts/nav" %>
<div class="banner_top_deco">
  <div class="banner-top-deco-inner-text">
    <div class="container" style="padding-bottom: 10px;">
      <div class="row mb-dp-none">
        <div class="banner-top-deco-header col-sm-12">
          Our Team
        </div>
        <div class="banner-top-deco-sub col-sm-12">
          
        </div>
      </div>
    </div>
  </div>
</div>


<%= render 'filter' %>


<div class="our-teams pages-card-padding">
  <div class="container">
    <div class="row">
        <%= render 'side_link' %>
      <div class="col-sm-9">
        <p class="about-us-header">Psychiatrist</p>
        <%= render 'teams' %>
      </div>

    </div>
  </div>
</div>
<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>

app/views/our_teams/psychology.html.erb
<%= render "layouts/nav" %>
<div class="banner_top_deco">
  <div class="banner-top-deco-inner-text">
    <div class="container" style="padding-bottom: 10px;">
      <div class="row mb-dp-none">
        <div class="banner-top-deco-header col-sm-12">
          Our Team
        </div>
        <div class="banner-top-deco-sub col-sm-12">
          
        </div>
      </div>
    </div>
  </div>
</div>


<%= render 'filter' %>


<div class="our-teams pages-card-padding">
  <div class="container">
    <div class="row">
        <%= render 'side_link' %>
      <div class="col-sm-9">
        <p class="about-us-header">Psychologists</p>
        <%= render 'teams' %>
      </div>

    </div>
  </div>
</div>
<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>

app/views/our_teams/show.html.erb
<%= render "layouts/nav" %>
<div class="banner_top_deco">
  <div class="banner-top-deco-inner-text">
    <div class="container" style="padding-bottom: 10px;">
      <div class="row mb-dp-none">
        <div class="banner-top-deco-header col-sm-12">
          Our Team
        </div>
        <div class="banner-top-deco-sub col-sm-12">
          
        </div>
      </div>
    </div>
  </div>
</div>


<div class="bread-crumb-border">
  <div class="container">
    <div class="row">
      <div class="bread-crumb col-sm-12">
        <div class="row justify-content-between">

          <div class="col-sm-6">
            <div id="custom-search-input">
                <div class="input-group col-md-12">
                    <input type="text" class="form-control input-lg" placeholder="Search" />
                    <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="button">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
                </div>
            </div>
          </div>

          <div class="col-sm-5" style="padding-right: 0px;">
            <span style="margin-right: 24px;">Filter by Department: </span>
              <select class="input-box" style="height: 48px; width: 265px;">
                <option value="volvo">Occupational Therapist</option>
                <option value="saab">Physical Therapist</option>
                <option value="opel">Kinesiologist</option>
                <option value="audi">Kinesiologist</option>
              </select>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>


<div class="our-teams pages-card-padding">
  <div class="container">
    <div class="row">
      <div class="col-sm-3 border-right">
        <div class="row align-items-center">
          <ul class="our-team-dp-list">
            <li><span class="dp-list-header">Departments</span></li>
            <li>All</li>
            <li>Office & Administration</li>
            <li>Therapists</li>
            <li>Kinesiologist</li>
            <li>Search</li>
          </ul>
        </div>
      </div>
      <div class="col-sm-9">
        <div class="row">
          <div class="col-lg-12 col-xl-4 mg-bt-20">
            <div class="card">
              <%= image_tag("team.png") %>
              <div class="card-body">
                <span class="font-lb bold">Edgar Emnacen</span>
                <p class="card-text font-size-sm">BScOT, CWCE</p>
                <p class="card-text font-size-sm">Registered Occupational Therapist</p>
              </div>
            </div>
          </div>
          <div class="col-lg-12 col-xl-8 mg-bt-20">
            <p class="about-us-header" style="margin-bottom: 2px;">Edgar Emnacen <span class="font-lb">BScOT, CWCE</span></p>
            <p class="card-text font-size-sm">Registered Occupational Therapist</p>
            <p>
              Edgar graduated in 1999 with a Bachelor of Science degree in Occupational Therapy. He is a Certified Work Capacity Evaluator (Roy Matheson and Associates). His current practice encompasses medical legal consultations, including Functional Capacity Evaluations, Cost of Future Care Assessments, and File Reviews.
            </p>
            <p>
              Edgar strives to maintain a balance between referrals from both Plaintiff and Defense counsels. He has qualified as an Expert Witness in the Supreme Court of British Columbia in the areas of Functional Capacity Evaluation, Work Capacity Evaluation, Cost of Future Care Analysis, Functional Analysis, Occupational Therapy and Ergonomics.
            </p>


            <div class="mg-top-20 section-desc">
              <p class="section-desc">
                Credentials
              </p>
            </div>
            <div>
              <div class="blue-dot"></div>Bachelor of Science, Occupational Therapy, <span class="bold-mx">University of British Columbia</span>, Vancouver, BC; 1999
            </div>
            <div>
              <div class="blue-dot"></div>Diploma, Business Administration, <span class="bold-mx">British Columbia Institute of Technology</span>, Burnaby, BC; 1996
            </div>
            <div>
              <div class="blue-dot"></div>Bachelor of Science, Biochemistry,<span class="bold-mx">University of British Columbia</span>, BC; 1993
            </div>
            <div class="mg-top-20 section-desc">
              <p class="section-desc">
                Current Practice Areas
              </p>
            </div>
            <div>
              <div class="blue-dot"></div>Medical Legal Functional Capacity Evaluations
            </div>
            <div>
              <div class="blue-dot"></div>Cost of Future Care Assessments
            </div>
            <div>
              <div class="blue-dot"></div>Medical Legal Consultations/File Reviews
            </div>
            <div>
              <div class="blue-dot"></div>Return to Work Support Services
            </div>
            <div class="mg-top-20 section-desc">
              <p class="section-desc">
                Current Practice Areas
              </p>
            </div>
            <div>
              <div class="blue-dot"></div>Full-time Registration, College Of Occupational Therapists of British Columbia
            </div>
            <div>
              <div class="blue-dot"></div>Full-time Member, Canadian Association of Occupational Therapists
            </div>
            <div>
              <div class="blue-dot"></div>Full-time Member, World Federation of Occupational Therapists
            </div>

            <div class="row padding-top-50">
              <div class="cta-see-team"> Download CV</div>
            </div>

          </div>
        </div>
      </div>

    </div>
  </div>
</div>
<%= render "layouts/bottom_cta_card" %>
<%= render "layouts/footer" %>